"""Discriminating adversarial enterprise authorization benchmark."""

from synthworld.enterprise.authorization.adversarial.baselines import (
    ENTERPRISE_ADVERSARIAL_AUTHORIZATION_BASELINES,
    AdversarialAuthorizationBaseline,
    binding_blind_authorization_baseline,
    clearance_blind_authorization_baseline,
    identifier_memorization_baseline,
    rbac_only_authorization_baseline,
    scope_blind_authorization_baseline,
    tenant_blind_authorization_baseline,
    time_blind_authorization_baseline,
)
from synthworld.enterprise.authorization.adversarial.common import (
    AdversarialAuthoritySource,
    AdversarialAuthorizationMechanism,
    AdversarialCaseCategory,
    AuthorityCombinationPolicy,
    TenantComparisonOperator,
)
from synthworld.enterprise.authorization.adversarial.metrics import (
    evaluate_enterprise_adversarial_authorization,
    perfect_enterprise_adversarial_authorization_prediction,
)
from synthworld.enterprise.authorization.adversarial.models import (
    AdversarialActionAttemptV1,
    AdversarialAttemptPredictionV1,
    AdversarialAttemptTruthV1,
    AdversarialAuthorityGrantV1,
    AdversarialCohortSummaryV1,
    AdversarialCounterfactualPairTruthV1,
    AdversarialCredentialBindingTruthV1,
    AdversarialCredentialEvidenceV1,
    AdversarialPrincipalV1,
    AdversarialResourceV1,
    AdversarialTenantRuleV1,
    EnterpriseAdversarialAuthorizationEvaluatorV1,
    EnterpriseAdversarialAuthorizationMetricsV1,
    EnterpriseAdversarialAuthorizationPolicyV1,
    EnterpriseAdversarialAuthorizationPredictionV1,
    EnterpriseAdversarialAuthorizationPublicV1,
)
from synthworld.enterprise.authorization.adversarial.reference import (
    ReferenceEnterpriseAdversarialAuthorizationV1,
    evaluate_adversarial_attempt,
    reference_enterprise_adversarial_authorization,
    resolve_adversarial_credential,
    validate_adversarial_authorization_artifacts,
)

__all__ = [
    "ENTERPRISE_ADVERSARIAL_AUTHORIZATION_BASELINES",
    "AdversarialActionAttemptV1",
    "AdversarialAttemptPredictionV1",
    "AdversarialAttemptTruthV1",
    "AdversarialAuthorityGrantV1",
    "AdversarialAuthoritySource",
    "AdversarialAuthorizationBaseline",
    "AdversarialAuthorizationMechanism",
    "AdversarialCaseCategory",
    "AdversarialCohortSummaryV1",
    "AdversarialCounterfactualPairTruthV1",
    "AdversarialCredentialBindingTruthV1",
    "AdversarialCredentialEvidenceV1",
    "AdversarialPrincipalV1",
    "AdversarialResourceV1",
    "AdversarialTenantRuleV1",
    "AuthorityCombinationPolicy",
    "EnterpriseAdversarialAuthorizationEvaluatorV1",
    "EnterpriseAdversarialAuthorizationMetricsV1",
    "EnterpriseAdversarialAuthorizationPolicyV1",
    "EnterpriseAdversarialAuthorizationPredictionV1",
    "EnterpriseAdversarialAuthorizationPublicV1",
    "ReferenceEnterpriseAdversarialAuthorizationV1",
    "TenantComparisonOperator",
    "binding_blind_authorization_baseline",
    "clearance_blind_authorization_baseline",
    "evaluate_adversarial_attempt",
    "evaluate_enterprise_adversarial_authorization",
    "identifier_memorization_baseline",
    "perfect_enterprise_adversarial_authorization_prediction",
    "rbac_only_authorization_baseline",
    "reference_enterprise_adversarial_authorization",
    "resolve_adversarial_credential",
    "scope_blind_authorization_baseline",
    "tenant_blind_authorization_baseline",
    "time_blind_authorization_baseline",
    "validate_adversarial_authorization_artifacts",
]
